paths:
  fastq_dir: ""
  cellranger_ref_dir: ""
  cellranger_exe: "~/pkg/cellranger-atac-2.1.0/bin/cellranger-atac"

out_dirs:
  atac: "atac_out"
  haystack: "haystack_out"

files:
  adt_catalog: ""
  hto_catalog: ""
  allowlist: ""

general:
  mode: "namesort"
  threads:
    cellranger_count: 12
    namesort: 8
  memory:
    cellranger_count: 120000
    namesort: 96000

samples:
  - ""

