paths:
  atac_fastq_dir: ""
  cellranger_ref_dir: ""
  cellranger_exe: "~/pkg/cellranger-atac-2.1.0/bin/cellranger-atac"

  adt_fastq_dir: ""
  adt_catalog: ""
  allowlist: ""

out_dirs:
  atac: "." # due to cellranger settings, this cannot be currently changed.
  haystack: "haystack_out"
  adt: "adt_out"

general:
  run_modes:
    atac: True # boolean
    atac_level: "namesort" # must be namesort or hhayystack
    adt: False # boolean

  library:
    cbc: [1,0,16]
    umi: [0,0,10]
    tag: [2,0,15]

  threads:
    cellranger_count: 12
    namesort: 8
    make_bus: 4
    sort_bus: 8

  memory:
    cellranger_count: 120000
    namesort: 96000
    make_bus: 36000

samples:
  - name: "A"
    adt_fastqs: ["A_S2_R1_001.fastq.gz", "A_S2_R2_001.fastq.gz", "A_S2_R3_001.fastq.gz"]
